-- DROP DATABASE blog_ipb23;
-- CREATE DATABASE blog_ipb23;
-- USE blog_ipb23;
-- CREATE TABLE posts (
-- id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
-- content VARCHAR(5500)
-- );
-- INSERT INTO posts 
-- (content)
-- VALUES
-- ("Apals abols uzkrita uz sipola"),
-- ("Abols ripo pa ielu un sipols paklup"),
-- ("Reali daudzkas iet greizi");
-- SELECT * FROM posts;